// <auto-generated />
namespace ASP.NET_MVC_EF_CRUD_Operation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class emp_app : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emp_app));
        
        string IMigrationMetadata.Id
        {
            get { return "202409301725196_emp_app"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
